default_context:
  project_name: 'binder-template'
  project_slug: 'binder-template'
  domain_main: 'binder-template.com'
  domain_staging: 'stag.binder-template.com'
  docker_swarm_stack_name_main: 'binder-template-com'
  docker_swarm_stack_name_staging: 'stag-binder-template-com'
  secret_key: '9cf8099360fc61c299514d29d3afa1439bd3cebd47c3eebfe0239dfc0609a3cf4e2da24bd1e87f19265f4c3705c746bf68e319de78ab27988859bb96dfda8614'
  first_superuser: 'admin@binder-template.com'
  first_superuser_password: '123'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.binder-template.com", "https://stag.binder-template.com", "https://binder-template.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@binder-template.com'
  postgres_password: '123'
  pgadmin_default_user: 'admin@binder-template.com'
  pgadmin_default_user_password: '123'
  traefik_constraint_tag: 'binder-template.com'
  traefik_constraint_tag_staging: 'stag.binder-template.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:123'
  sentry_dsn: ''
  docker_image_prefix: 'binder'
  docker_image_backend: 'binderbackend'
  docker_image_celeryworker: 'binderceleryworker'
  docker_image_frontend: 'binderfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
